### ISSUE TITLE
mame full set nonmerged without chd

### ISSUE THREAD

**Issue by Mitch187** [Voljega/BestArcade#11]
Hello,

i only have a 0.251 fullset for my libretro-mame and i don't have a chd archive (it's just too big for me and i tested some roms with chd and what can i say, they run too slow on my 2400ge mini pc. Is it somehow possible to exclude the ROMs that need a CHD (based on Best Arcade). How can I still filter out these ROMs afterwards? 

Best Regards,
Mitch

**Comment by Voljega** [comment]
Not at the moment but its feasible this is something I could implement
later in august or september

**Comment by Voljega** [comment]
Actually if you look at the mame list on the google sheet for N100 MiniPC
there's an extra colulmn indicating if a game has a chd or not, so in the
menantime you could even do it yourself

**Comment by Mitch187** [comment]
Thank you for your quick answer.

**Comment by Voljega** [comment]
[available in latest release](https://github.com/Voljega/BestArcade/releases/tag/1.7)
