### ISSUE TITLE
[Issue] Konami 4 player roms should not be considered the "best" version

### ISSUE THREAD

**Issue by Daeymon** [Voljega/BestArcade#14]
Many Konami "4 player" roms (which are usually the parents within the cloneset) lock a specific ingame character to each of the players. An example being the "simpsons" rom. With this "4 player" rom, "player 1" will always have to play as Marge. The original concept behind this, is each different ingame character on the physical arcade machine had its own coin slot. So you picked your character based on picking to be player 1, 2, 3 or 4 and putting your money in the slot of the character you wanted to play as.

In an emulated situation switching whether you are player 1, 2, 3 or 4 is not ideal and just isn't the "best" experience. With one of the "2 player" rom clones, the user instead gets to choose which character they wish to play as within the game. From my point of view, this would be considered the "best" experience when it came to emulation.

This happens with many of the Konami roms, including the Teenage Mutant Ninja Turtle ones.

**Comment by Voljega** [comment]
OK I can include the 2 players roms as well

I guess the relevant games are:
- The Simpsons
- X-Men
- TMNT

are they any other ?

**Comment by Daeymon** [comment]
These are the manual adjustments I currently make to the output:

simpsons -> simpsons2p3
ssriders -> ssridersebd
tmnt -> tmnt2po
tmnt2 -> tmnt22pu

The X-Men default is fine.

**Comment by Voljega** [comment]
OK I also added the XMen 6 players version

Should be released in next version

**Comment by Voljega** [comment]
[available in latest release](https://github.com/Voljega/BestArcade/releases/tag/1.7)
