### ISSUE TITLE
fbneo list

### ISSUE THREAD

**Issue by barbudreadmon** [Voljega/BestArcade#2]
So i tested all games currently listed as not launching or crashing at https://docs.google.com/spreadsheets/d/1S5qAI-TEl7wfqg6w9VNEwKciMGUtw40n9PS4xslkG3s/edit#gid=423376617 : 

gollygho
hunchbak
f1dream
choplift
hachamf
nob
fsoccer
huncholy
tdfever
tdfever2
=> those games are flagged as not working (see https://github.com/libretro/FBNeo/blob/master/gamelist.txt), so it's expected that they won't launch

blocken
gigasm2
pasha2
sb2003
heberpop
crazywar
gondou (might require gondo parent if you are using split romsets)
=> all those games worked (are you sure your romsets match the version you were trying ?), some of them are too slow for rpi3 though (sb2003 took a long time rendering first image)

Tried a few games marked as having control issues but quickly stopped because it looked like i wouldn't find any emulation issue either : 
- arknoid2 => default sensibility seemed pretty fine to me ? and you can still fine-tune it through core options or retroarch settings
- opwolf3 => aim works out-of-the-box ? maybe you messed up something while tinkering with service settings ? try deleting opwolf3.fs maybe ?
- lghost => i can understand this one being a bit annoying, but the instructions for getting out of the calibrating screen are actually on screen
- bubbletr => the game is actually tagged as not working, it's kinda weird you could even launch it

**Comment by Voljega** [comment]
Hello @barbudreadmon, thanks for the feeback

I wil examine all that later (and now the pi3 is replaced by a N2) but I can already tell you some things :
- The romset is late may, verified on ClrMamePro with the dat generated from the latest FBNeo windows version  at the time (31st of May), everything was green, just a few King of Fighters hacks missing and some jackie chan roms marked as red, but they manage to work though
- Embedded version in Batocera is supposed to be 27th May, but the last few games from second half of may don't work, so there might be some issue here
- Still for the second block, none of them work... maybe we could compare CRC32/MD5 is you also have a non-merged set ?
- For gondo /gondou here is what I have in the dat :
```
<game name="gondou" cloneof="zzyzzyxx" romof="zzyzzyxx">
		<description>Gondomania (US)</description>
		<year>1987</year>
		<manufacturer>Data East USA</manufacturer>
		<rom name="dt00.f3" size="32768" crc="a8cf9118"/>
		<rom name="dt01.f5" size="65536" crc="c39bb877"/>
		<rom name="dt02.f6" size="65536" crc="bb5e674b"/>
		<rom name="dt03.f7" size="65536" crc="99c32b13"/>
		<rom name="dt05.h5" size="32768" crc="ec08aa29"/>
		<rom name="dt14.b18" size="32768" crc="4bef16e1"/>
		<rom name="dt19.f13" size="65536" crc="da2abe4b"/>
		<rom name="dt20.f15" size="32768" crc="42d01002"/>
		<rom name="dt16.f9" size="65536" crc="e9955d8f"/>
		<rom name="dt18.f12" size="32768" crc="c0c5df1c"/>
		<rom name="dt15.f8" size="65536" crc="a54b2eb6"/>
		<rom name="dt17.f11" size="32768" crc="3bbcff0d"/>
		<rom name="dt21.f16" size="65536" crc="1c5f682d"/>
		<rom name="dt22.f18" size="32768" crc="c1876a5f"/>
		<rom name="dt08.h10" size="65536" crc="aec483f5"/>
		<rom name="dt09.h12" size="32768" crc="446f0ce0"/>
		<rom name="dt06.h7" size="65536" crc="3fe1527f"/>
		<rom name="dt07.h9" size="32768" crc="61f9bce5"/>
		<rom name="dt12.h16" size="65536" crc="1a72ca8d"/>
		<rom name="dt13.h18" size="32768" crc="ccb81aec"/>
		<rom name="dt10.h13" size="65536" crc="cfcfc9ed"/>
		<rom name="dt11.h15" size="32768" crc="53e9cf17"/>
		<rom name="dt-a.b1" size="4096" crc="03abceeb"/>
		<rom name="ds-23.b10" size="1024" crc="dcbfec4e"/>
		<driver status="good"/>
	</game>
```
and `gondo` is nowhere to be found in the dat nor in the romset I have.... besides it is a non-merged romset so `gondou` should still work even without `zzyzzyxx` ?

- For `lghost` and `loffire` yeah I left it like that because I didn't have a second controller on hand a t the time but I will test with one
I didn't touch anything at all for any game in the service menu, for `opwolf3` or for anything else, I corrected this after retesting on N2 though, I didn't have this aim problem in the past if I remember well

- Lastly just a technical question but most of the parent roms of the first block work in mame2003plus or mame2010, pretty old romsets and mame version, is there any critical reason why they are not supported by FbNeo ?

**Comment by barbudreadmon** [comment]
It seems gondou indeed wouldn't load in non-debug builds before the fix in https://github.com/libretro/FBNeo/commit/d3dab430c850f525ccbdf97b943301ec974fb5f9

For the others, everything related to crc mismatch should be pointed at in the logs. I don't know much about batocera (all tests were done with current fbneo on retropie rpi3 & retroarena n2), they could be breaking the games through unsafe cflags.

**Comment by Voljega** [comment]
OK I will try to have a look at that, see if there's anything in the logs

**Comment by Voljega** [comment]
I tried with `blocken` and `heberpop` and here's what I have in both case, not much, even if retroarch seems to be launched in verbose mode :
```
2020-06-13 16:23:34 INFO (emulatorlauncher.py:170):runCommand(): command: ['/usr/bin/retroarch', '-L', '/usr/lib/libretro/fbneo_libretro.so', '--config', '/userdata/system/configs/retroarch/retroarchcustom.cfg', '--set-shader', '/usr/share/batocera/shaders/crt/zfast-crt.glslp', '--verbose', '/userdata/roms/fbneo/[Puzzle]/heberpop.zip']
2020-06-13 16:23:34 INFO (emulatorlauncher.py:171):runCommand(): env: {'logo': 'osd0,loaded', 'disablehpd': 'false', 'HOME': '/userdata/system', 'PATH': '/sbin:/usr/sbin:/bin:/usr/bin', 'SDL_NOMOUSE': '1', 'LANG': 'en_US.UTF-8', 'TERM': 'linux', 'SHELL': '/bin/sh', 'LANGUAGE': '', 'hdmimode': 'custombuilt', 'SHLVL': '3', 'PREVLEVEL': 'N', 'label': 'BATOCERA', 'cvbsmode': '576cvbs', 'max_freq_a73': '1800', 'CONSOLE': '/dev/console', 'max_freq_a53': '1896', 'modeline': '1920,1080,148500,67500,60,1920,2008,2052,2200,1080,1084,1089,1125,1,1,1', 'monitor_onoff': 'false', '_': '/usr/bin/python', 'sdrmode': 'auto', 'hdmitx': 'cec3f', 'OLDPWD': '/', 'voutmode': 'hdmi', 'overscan': '100', 'PWD': '/userdata', 'cvbscable': '', 'RUNLEVEL': 'S', 'INIT_VERSION': 'sysvinit-'}
[INFO] RetroArch 1.8.6 (Git 1661b2ea6c)
[INFO] Redirecting save file to "/userdata/saves/fbneo/heberpop.srm".
[INFO] Redirecting save state to "/userdata/saves/fbneo/heberpop.state".
[INFO] === Build =======================================
[INFO] Capabilities:  ASIMD
[INFO] Built: May 24 2020
[INFO] Version: 1.8.6
[INFO] Git: 1661b2ea6c
[INFO] =================================================
[INFO] Loading dynamic libretro core from: "/usr/lib/libretro/fbneo_libretro.so"
[INFO] [Overrides] no core-specific overrides found at /userdata/system/.config/retroarch/config/FinalBurn Neo/FinalBurn Neo.cfg.
[INFO] [Overrides] no content-dir-specific overrides found at /userdata/system/.config/retroarch/config/FinalBurn Neo/[Puzzle].cfg.
[INFO] [Overrides] no game-specific overrides found at /userdata/system/.config/retroarch/config/FinalBurn Neo/heberpop.cfg.
[INFO] [Remaps]: remap directory: /userdata/system/.config/retroarch/config/remaps
[INFO] Redirecting save file to "/userdata/saves/fbneo/heberpop.srm".
[INFO] Redirecting save state to "/userdata/saves/fbneo/heberpop.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] Content loading skipped. Implementation will load it on its own.
[libretro INFO] Setting save dir to /userdata/saves/fbneo
[INFO] [Environ]: SYSTEM_DIRECTORY: "/userdata/bios/".
[libretro INFO] Setting system dir to /userdata/bios/
[ERROR] Failed to load content
[INFO] Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] Unloading game..
[INFO] Unloading core..
[INFO] Unloading core symbols..
2020-06-13 16:23:35 INFO (emulatorlauncher.py:223):<module>: Exiting configgen with status 1
```

**Comment by barbudreadmon** [comment]
It doesn't seem your fbneo version supports those games (they were added on 12 may though), what's the hash (bottom left of RA menu) of the fbneo commit you are using ?

**Comment by Voljega** [comment]
this what I have :
https://github.com/batocera-linux/batocera.linux/commit/26519c9f079b10b8358214f7b42b0de468104f36#diff-4db6a653428fc1852d05b77d8502c154

date seems wrong or last games should work, is the id usefull ?

**Comment by barbudreadmon** [comment]
Are you sure it's the commit hash at the bottom left of your RA menu ?

**Comment by Voljega** [comment]
I've got `1661b2ea6c` at the bottom left of the RA menu

**Comment by barbudreadmon** [comment]
That's the retroarch hash, i want the fbneo hash, it should be under the form "FinalBurn Neo (v0.2.97.44 hash)", you need the core launched for it to appear.

PS : it might not appear with the rgui menu driver, you need xmb or ozone

**Comment by Voljega** [comment]
Yes, this hash is actually ingame during launching a game with FBNeo :

![IMG_20200614_113759226](https://user-images.githubusercontent.com/1405681/84590115-0eea7400-ae34-11ea-90db-ae147861e49c.jpg)

**Comment by barbudreadmon** [comment]
Ok, well, there is no commit with that hash in FBNeo's repository... meaning i don't know what you are using... so there is no way to know from whence your version is based, neither what games it's supposed to support or not...

That's crazy shit if you ask me, and after seeing that crap you can be sure i'll never use or recommend batocera to anyone... Anyway, if you use a proper distro which use my repo **unmodified**, those games will work properly.

**Comment by Voljega** [comment]
Yeah I came to the same conclusion, quite strange....

Maybe it's just a simple mistake, or a patch on Batocera's side changing the hash or something... I'll ask the team

**Comment by barbudreadmon** [comment]
Is batocera showing the right commit hash nowaday ? I'm on discord with another batocera user... it doesn't seem batocera is providing usable dat files... it appears the files exist but are empty... this is trolling if you ask me...

**Comment by Voljega** [comment]
Ahahah sorry for this, haven't looked into the commit hash since last year as I did report the problem to them at the time and they choose to get flustered about what you said instead of looking into the problem, which is pretty usual for them...

Will report the dat issue though

**Comment by Voljega** [comment]
someone posted this :
![IMG_20210609_152604](https://user-images.githubusercontent.com/1405681/121367412-9761fe80-c93a-11eb-87ab-fdecfe786ce4.jpg)

**Comment by Voljega** [comment]
Seems it doesn't correspond to any axitsing commit. again.

**Comment by barbudreadmon** [comment]
> Seems it doesn't correspond to any axitsing commit. again.

Indeed... then i guess there is still no way to figure out the right romsets for FBNeo on batocera, except by luck...

**Comment by Voljega** [comment]
one of them is saying :
```
probably because we build outside a GIT repository cloned
and it uses git retrieve proper commit number and revision
```

another is claiming it's because you use push force on your repo and it's changing or deleting past commit ids which then doesn't exist but couldn't explain why the issue would only appear on Batocera

and if you use push force only for rebasing I'm not sure this is even true

**Comment by Voljega** [comment]
Seems they found the fix, should be commited to master soon, might take a while to be integrated in a release though

**Comment by barbudreadmon** [comment]
Push force doesn't delete past commits in the first place, it just make them disappear from the commit history, but they would still be accessible through the right url. I never use that stuff anyway on master branch because the libretro bot doesn't like that.
